/* Generated By:JavaCC: Do not edit this line. AFCcomposerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AFCcomposerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DEBUT = 5;
  /** RegularExpression Id. */
  int FIN = 6;
  /** RegularExpression Id. */
  int INTERFACE = 7;
  /** RegularExpression Id. */
  int COMP = 8;
  /** RegularExpression Id. */
  int PROP = 9;
  /** RegularExpression Id. */
  int EVT = 10;
  /** RegularExpression Id. */
  int INV = 11;
  /** RegularExpression Id. */
  int INIT = 12;
  /** RegularExpression Id. */
  int ACT = 13;
  /** RegularExpression Id. */
  int THEN = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int PROPRIETAIRE = 16;
  /** RegularExpression Id. */
  int TYPE = 17;
  /** RegularExpression Id. */
  int PROPERTYTYPE = 18;
  /** RegularExpression Id. */
  int NOMACTIONUTILISATEUR = 19;
  /** RegularExpression Id. */
  int LETTRE = 20;
  /** RegularExpression Id. */
  int NOMBRE = 21;
  /** RegularExpression Id. */
  int ID = 22;
  /** RegularExpression Id. */
  int COMPARAISON = 23;
  /** RegularExpression Id. */
  int AFFECTATIONOperation = 24;
  /** RegularExpression Id. */
  int ACCOLADEOuvrante = 25;
  /** RegularExpression Id. */
  int ACCOLADEFermante = 26;
  /** RegularExpression Id. */
  int SEPARATEUR = 27;
  /** RegularExpression Id. */
  int DeuxPoints = 28;
  /** RegularExpression Id. */
  int PLUS = 29;
  /** RegularExpression Id. */
  int APOSTROPHE = 30;
  /** RegularExpression Id. */
  int ACCESATTRIBUT = 31;
  /** RegularExpression Id. */
  int TILDE = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"DEBUT\"",
    "\"FIN\"",
    "\"INTERFACE\"",
    "\"COMP\"",
    "\"PROP\"",
    "<EVT>",
    "\"INV\"",
    "\"INITIALISATIONS\"",
    "\"ACTIONS\"",
    "<THEN>",
    "<IF>",
    "<PROPRIETAIRE>",
    "<TYPE>",
    "<PROPERTYTYPE>",
    "<NOMACTIONUTILISATEUR>",
    "<LETTRE>",
    "<NOMBRE>",
    "<ID>",
    "<COMPARAISON>",
    "\":=\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\":\"",
    "\"+\"",
    "\"\\\'\"",
    "\"::\"",
    "\"~\"",
    "\", \"",
    "\".\"",
  };

}
